"""CLI: generate the 50-route demonstration case-study scenario. See
`quantumfleet.data_generation.scenario_generator` for the archetype
distributions and the emission-cap calibration method.

Usage:
    python scripts/generate_case_study_scenario.py [--seed N] [--output PATH]
"""

import argparse
from pathlib import Path

import yaml

from quantumfleet.data_generation.scenario_generator import build_scenario
from quantumfleet.prediction.physics_model import load_vessel_catalog

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--vessel-catalog", default=str(PROJECT_ROOT / "configs" / "vessel_types.yaml"))
    parser.add_argument("--output", default=str(PROJECT_ROOT / "configs" / "demo_case_study.yaml"))
    args = parser.parse_args()

    vessel_classes, speed_bins = load_vessel_catalog(args.vessel_catalog)
    scenario = build_scenario(vessel_classes, speed_bins, seed=args.seed, name="demo_case_study")

    header = (
        "# Auto-generated by scripts/generate_case_study_scenario.py -- do not hand-edit\n"
        "# route distances/demands. emission_cap_tonnes_co2e IS calibrated (not guessed):\n"
        "# see quantumfleet.data_generation.scenario_generator for the method.\n"
    )
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(scenario, f, sort_keys=False)
    print(f"Wrote {len(scenario['routes'])} routes to {args.output}")


if __name__ == "__main__":
    main()
